### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/owasp/esapi/errors/EncodingException

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#227]
_From [shilpi.a...@gmail.com](https://code.google.com/u/108155155500833528712/) on April 20, 2011 02:52:37_

What steps will reproduce the problem? 1.Use Validator.validateInput method for some validation. some people are facing error 
2. Error comes 
java.lang.NoClassDefFoundError: org/owasp/esapi/errors/EncodingException 3. What is the expected output? What do you see instead? Class not found error should not come. 
java.lang.NoClassDefFoundError: org/owasp/esapi/errors/EncodingException What version of the product are you using? On what operating system? esapi-2.0_rc10 Does this issue affect only a specified browser or set of browsers? Please provide any additional information below. The class is there in classpath. I don't see why this error should be coming.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=218_

**Comment by shahshikha630** [comment]
Is this issue resolved? Any workaround to fix this one in application?

**Comment by kwwall** [comment]
This issue doesn't have enough information provided to duplicate it.
Perhaps you can provide a test case to replicate the issue? If so, please
do so.

-kevin

**Comment by xeno6696** [comment]
This issue always turns out to be a local environmental issue.  research what causes NoClassDefFound and solve your class path problem.

**Comment by shahshikha630** [comment]
In my application, the functionality is to upload an excel file. After upgrading my application to spring framework 5.3.15, this functionality broke. My application is on JDK 8. I upgraded esapi library to the latest one but still getting the same thing. I checked my classpath, the esapi is there. It is giving me below error:
```
io.netty.handler.codec.DecoderException: java.lang.NoClassDefFoundError: org/owasp/esapi/errors/EncodingException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278) ~[netty-all-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147) ~[netty-all-4.0.24.Final.jar:4.0.24.Final]
```

**Comment by xeno6696** [comment]
This is an issue with Netty.  You need to ask them.  They’re using ESAPI and whatever you’re doing is conflicting with their usage.

**Comment by xeno6696** [comment]
If you can construct a dummy application that reproduces this, I can help troubleshoot but otherwise I’d have to be present in your cube.

**Comment by jeremiahjstacey** [comment]
Might be worth pointing out that the netty 4.0.24-Final version is 10 years old and has no direct dependencies on ESAPI
https://mvnrepository.com/artifact/io.netty/netty-all/4.0.24.Final
https://repo1.maven.org/maven2/io/netty/netty-all/4.0.24.Final/netty-all-4.0.24.Final.pom

I've poked through several of the netty projects under [io.netty](https://mvnrepository.com/artifact/io.netty) for that version and I do not see any direct reference to ESAPI.

Based on the stack and the lack of a direct dependency, My guess is that there is an in-house decoder implementation that's been plugged into netty that uses ESAPI to support the process.

As @xeno6696 stated though, this appears to be environmental and difficult to diagnose from the current information.

**Comment by kwwall** [comment]
Indeed, that is largely why I asked for a test case to replicate this
issue. We probably should have closed this long ago as being unable to
reproduce and just didn't notice it since it was so old. (Sort of like me,
but that's a story for another time.  😜)

-kevin
