### ISSUE TITLE
DefaultEncoder.canonicalize() Bug

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#291]
_From [victropo...@gmail.com](https://code.google.com/u/115750941553058253493/) on August 30, 2012 16:03:42_

What steps will reproduce the problem? 1.  Attempt to validate the following HTTPQueryString:

connectid=68470072-44c2-417b-822b-d945dc0364f4&request=GetFeature&service=wfs&version=1.1.0&typeName=DigitalGlobe&#37;3AFinishedFeature&bbox=37.5&#37;2C41.5&#37;2C37.8&#37;2C41.7&PROPERTYNAME=source&#37;2CsourceUnit&#37;2CproductType
1.  Notice the following exception get logged:

2012-08-30 00:02:25,918 WARN  [388e3f54-b1be-442c-a124-45f9fcda7c67] [http-8082-10] [IntrusionDetector] - [SECURITY FAILURE Anonymous:null@unknown -> /OnlinePortfolio/IntrusionDetector] Invalid input: context=com.digitalglobe.dgp.wfs.controller.WfsController, type(HTTPQueryString)=^[a-zA-Z0-9()-=*.\?;,+\/:&_ &#37;#-=]_$, input=connectid=68470072-44c2-417b-822b-d945dc0364f4&request=GetFeature&service=wfs&version=1.1.0&typeName=DigitalGlobe:FinishedFeature&bbox=37.5,41.5,37.8,41.7∝ERTYNAME=source,sourceUnit,productType, orig=connectid=68470072-44c2-417b-822b-d945dc0364f4&request=GetFeature&service=wfs&version=1.1.0&typeName=DigitalGlobe&#37;3AFinishedFeature&bbox=37.5&#37;2C41.5&#37;2C37.8&#37;2C41.7&PROPERTYNAME=source&#37;2CsourceUnit&#37;2CproductType
org.owasp.esapi.errors.ValidationException: com.digitalglobe.dgp.wfs.controller.WfsController: Invalid input. Please conform to regex ^[a-zA-Z0-9()-=\_.\?;,+\/:&_ &#37;#-=]*$ with a maximum length of 1024
        at org.owasp.esapi.reference.validation.StringValidationRule.checkWhitelist(StringValidationRule.java:144)
        at org.owasp.esapi.reference.validation.StringValidationRule.getValid(StringValidationRule.java:306)
        at org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:213)
        at org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:185)
1.  Notice that &PROP has been converted to ∝ by the canonicalize method.
2.  If you repeat but put the PROPERTYNAME parameter at the beginning of the query string (i.e. without the &), it works fine. What is the expected output? What do you see instead? The expected output is that the &PROP is not converted. What version of the product are you using? On what operating system? 2.0GA

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=285_

**Comment by xeno6696** [comment]
@kwwall I think [this commit](https://github.com/ESAPI/esapi-java-legacy/commit/aafa3539002e01cc40b7d12868ab043838e62563), associated with issue #376 will fix this issue as well.  The problem was that when canonicalizing a URI, ESAPI treats the URI as a single-syntax string, ignoring URI structure.  &parameter=foo is legal in a URI query.

**Comment by kwwall** [comment]
@xeno6696 So, do we have a test case to test this specific scenario originally described in this issue? If so and it's doing the right thing, I think you can close it. Otherwise, we need a plan B.

**Comment by xeno6696** [comment]
We don't, but we will...

**Comment by xeno6696** [comment]
The given input that failed was actually failing due to the commas not being URI encoded.  Commas are not legal URI syntax, so the original coder was still going to have a problem.  At any rate, the input is included in the test now.
