### ISSUE TITLE
java.io.FileNotFoundException Error in Logs When ESAPI.properties and validation.properties are in resources. and the application is up ,features are not  working.

### ISSUE THREAD

**Issue by sh26masood** [ESAPI/esapi-java-legacy#831]
ESAPI: WARNING: System property [org.owasp.esapi.opsteam] is not set
ESAPI: WARNING: System property [org.owasp.esapi.devteam] is not set
ESAPI: Attempting to load ESAPI.properties via file I/O.
ESAPI: Attempting to load ESAPI.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: C:\Users\shemasoo\cisco project\partner_self_service_internal\ESAPI.properties
ESAPI: Not found in SystemResource Directory/resourceDirectory: .esapi\ESAPI.properties
ESAPI: Not found in 'user.home' (C:\Users\shemasoo) directory: C:\Users\shemasoo\esapi\ESAPI.properties
ESAPI: Loading ESAPI.properties via file I/O failed. Exception was: java.io.FileNotFoundException
ESAPI: Attempting to load ESAPI.properties via the classpath.
ESAPI: SUCCESSFULLY LOADED ESAPI.properties via the CLASSPATH from '/ (root)' using current thread context class loader!
ESAPI: SecurityConfiguration for Validator.ConfigurationFile.MultiValued not found in ESAPI.properties. Using default: false
ESAPI: Attempting to load validation.properties via file I/O.
ESAPI: Attempting to load validation.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: C:\Users\shemasoo\cisco project\partner_self_service_internal\validation.properties
ESAPI: Not found in SystemResource Directory/resourceDirectory: .esapi\validation.properties
ESAPI: Not found in 'user.home' (C:\Users\shemasoo) directory: C:\Users\shemasoo\esapi\validation.properties
ESAPI: Loading validation.properties via file I/O failed.
ESAPI: Attempting to load validation.properties via the classpath.
ESAPI: SUCCESSFULLY LOADED validation.properties via the CLASSPATH from '/ (root)' using current thread context class loader!
org.owasp.esapi.errors.ConfigurationException: java.lang.reflect.InvocationTargetException Encoder class (org.owasp.esapi.reference.DefaultEncoder) CTOR threw exception.
	at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:129)
	at org.owasp.esapi.ESAPI.encoder(ESAPI.java:101)
	at com.cisco.is.pae.util.PAEUtil.getSanitizedParameter(PAEUtil.java:236)
	at com.cisco.common.LDAPUtil.getAccessLevelFromLDAP(LDAPUtil.java:388)
	at com.cisco.common.LDAPUtil.main(LDAPUtil.java:415)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:86)
	... 4 more
Caused by: org.owasp.esapi.errors.ConfigurationException: java.lang.ClassNotFoundException: org.owasp.esapi.reference.JavaLogFactory LogFactory class (org.owasp.esapi.reference.JavaLogFactory) must be in class path.
	at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:108)
	at org.owasp.esapi.ESAPI.logFactory(ESAPI.java:139)
	at org.owasp.esapi.ESAPI.getLogger(ESAPI.java:155)
	at org.owasp.esapi.reference.DefaultEncoder.<init>(DefaultEncoder.java:85)
	at org.owasp.esapi.reference.DefaultEncoder.<init>(DefaultEncoder.java:109)
	at org.owasp.esapi.reference.DefaultEncoder.getInstance(DefaultEncoder.java:68)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.owasp.esapi.reference.JavaLogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.owasp.esapi.util.ObjFactory.loadClassByStringName(ObjFactory.java:158)
	at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:81)
	... 14 more

**Comment by sh26masood** [comment]
in a project how can we run this  java  -Dorg.owasp.esapi.logSpecial.discard=true

**Comment by xeno6696** [comment]
so -D has to be added however your application runs on your machine.  

If you run in command line:

`java -Dorg.owasp.esapi.logSpecial.discard=true myApp.jar`

Otherwise if its running tomcat or Jetty locally  you need to check your webserver's documentation as to how to pass in "-D" properties.

**Comment by xeno6696** [comment]
Otherwise, without a project duplicating your behavior that Kevin or I can just clone and run locally, there isn't much to go on here.

**Comment by kwwall** [comment]
One important observation: Looks as though you perhaps promoted a previous version of **ESAPI.properties** without carefully reading the release notes when you upgraded your ESAPI version. Why do I think that? Because of this in your exception stack trace:
```
 Caused by: org.owasp.esapi.errors.ConfigurationException: java.lang.ClassNotFoundException: org.owasp.esapi.reference.JavaLogFactory LogFactory class (org.owasp.esapi.reference.JavaLogFactory) must be in class path.
```
Note that it is referring to `org.owasp.esapi.reference.JavaLogFactory`, but that class name was moved to a different package long ago. Find your **ESAPI.propertie**s file, look for your **ESAPI.Logger** property, and change the value from `org.owasp.esapi.reference.JavaLogFactory` to `org.owasp.esapi.logging.java.JavaLogFactory` and that will likely fix your problem.

Note more details are given at https://github.com/ESAPI/esapi-java-legacy/wiki/Configuration-Reference:-JavaLogFactory

**Comment by sh26masood** [comment]
@kwwall  i used maven dependency added in project , and easpi.properties that all i downloaded from github EASPI legacy and i downloaded added in resource folder , after using that sanitize parameter it is giving error

**Comment by kwwall** [comment]
We need more information to help you with this. What version of ESAPI are you using? What does your **ESAPI.Logger** property file say? It needs to be `org.owasp.esapi.logging.java.JavaLogFactory`. If it says that, you are picking up a different **ESAPI.properties** file then the one you are intending to use (e.g., there may be one bundled as a resource in another direct or transitive jar that Maven pulls in) or some other dependency has made a direct reference to `org.owasp.esapi.reference.JavaLogFactory`. Maybe run '\`mvn -B dependency:tree` and check the output. If are you using any some dependency (e.g., OpenSAML, Shibboleth, etc.) that might be using a old version of ESAPI, that could be causing the problem.

**Comment by sh26masood** [comment]
thanks a lot @kwwall  got it worked at last ,we  need  to add Easpi.properties  file based on the same version  what you have released
